[tool.poetry]
name = "etl"
version = "0.1.0"
description = ""
authors = ["Sharafutdinov Danis <sharafutdinovv.danis@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.11.7"
tenacity = "^9.1.2"
click = "^8.2.1"
psycopg2-binary = "^2.9.10"
ruff = "^0.12.1"
pydantic-settings = "^2.10.1"
sqlalchemy = "^2.0.41"
elasticsearch = "8.18.1"
redis = "^6.2.0"
polyfactory = "^2.22.0"
psycopg = "^3.2.9"


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
coverage = "^7.9.2"
pytest-cov = "^6.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "."
addopts = "--cov=app tests"
[tool.coverage.run]
source = ["app"]
omit = [
    "app/alembic/*",
    "app/adapters/cli/*",
]
command_line = "-m pytest -vv -W error::sqlalchemy.exc.SAWarning -W error::sqlalchemy.exc.SADeprecationWarning"
branch = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "class .*\\(.*\\bProtocol\\b.*\\):",
    "@(?:typing\\.)?overload",
    "if TYPE_CHECKING:",
    "raise NotImplementedError",
]
show_missing = true
skip_covered = true
skip_empty = true
precision = 2
# fail_under = 85